Repository atlp-rwanda/atlp-devpulse-bn, pull requests merged in 2024-10, with the labels that each got.

#108 #148 Add Email verification after registration
  .env.example
  src/models/AuthUser.ts
  src/resolvers/loginUserResolver.ts
  src/resolvers/programResolver.ts
  src/schema/loggedUser.ts
  src/seeders/users.ts
Labels: Ready For Review, BYTE SWAT

#105 Will fix form resolver
  src/resolvers/forms.resolver.ts
  src/utils/controllers/userController.ts
Labels: Ready For Review, DREAM TEAM

#112 Extending information which user can update
  src/resolvers/loginUserResolver.ts
  src/schema/loggedUser.ts
Labels: Ready For Review, DREAM TEAM

#111 Have a trainee be able to apply with basic data
  src/models/traineeAttribute.ts
  src/resolvers/traineeApplicantResolver.ts
  src/resolvers/traineeAttributeResolver.ts
  src/schema/traineeApplicantSchema.ts
  src/schema/traineeAttributeSchema.ts
Labels: Ready For Review, DREAM TEAM

#107 reset and forget password #147
  package.json
  src/index.ts
  src/models/AuthUser.ts
  src/models/user.ts
  src/resolvers/forgetpassword.ts
  src/schema/forgetpassword.ts
Labels: Ready For Review, BYTE SWAT

#113 #148 Fix email verification
  src/resolvers/loginUserResolver.ts
Labels: Ready For Review, BYTE SWAT

#114 #151 Applicant be able to apply job
  .env.example
  package.json
  src/index.ts
  src/models/appliedJob.ts
  src/models/session.ts
  src/models/trackAppliedJob.ts
  src/resolvers/appliedJobResolver.ts
  src/schema/appliedJobTypeDefs.ts
  src/seeders/users.ts
Labels: Ready For Review, BYTE SWAT

#109 Ft applicant dashboard
  src/index.ts
  src/models/AuthUser.ts
  src/models/attendanceModel.ts
  src/models/cohortModel.ts
  src/models/performanceModel.ts
  src/models/traineeApplicant.ts
  src/models/user.ts
  src/resolvers/attendanceResolver.ts
  src/resolvers/loginUserResolver.ts
  src/resolvers/performanceResolver.ts
  src/resolvers/traineeApplicantResolver.ts
  src/schema/attendanceSchema.ts
  src/schema/cohortScheme.ts
  src/schema/loggedUser.ts
  src/schema/performanceSchema.ts
  src/schema/traineeApplicantSchema.ts
  src/schema/userLoginSchema.ts
  src/seeders/applicationcycle.ts
  src/seeders/users.ts
Labels: Ready For Review, BYTE SWAT

#115 #147 Implementing google authentication
  src/index.ts
  src/models/AuthUser.ts
  src/resolvers/loginUserResolver.ts
  src/schema/loggedUser.ts
  src/utils/controllers/userController.ts
Labels: Ready For Review, BYTE SWAT

#124 applicant notifications
  package.json
  src/helpers/pusher.ts
  src/index.ts
  src/models/applicantNotifications.ts
  src/resolvers/applicantNotifications.ts
  src/resolvers/applicationCycleResolver.ts
  src/resolvers/jobPostResolvers.ts
  src/schema/applicantNotifications.ts
Labels: Ready For Review, BYTE SWAT

#120 Fixing job application process
  package.json
  src/database/db.config.ts
  src/index.ts
  src/models/appliedJob.ts
  src/models/formsModel.ts
  src/models/jobModels.ts
  src/resolvers/DelTranee.ts
  src/resolvers/appliedJobResolver.ts
  src/resolvers/candidateApplicationResolver.ts
  src/resolvers/filterJob.ts
  src/resolvers/filterTraineeResolver.ts
  src/resolvers/forms.resolver.ts
  src/resolvers/programResolver.ts
  src/schema/appliedJobTypeDefs.ts
  src/schema/formJobSchema.ts
  src/schema/formSchema.ts
  src/seeders/jobs.ts
  src/seeders/users.ts
  src/utils/cronJob.ts
Labels: work-in-progress, BYTE SWAT

#121 Admin application list seeders
  src/seeders/applicationCyle.ts
  src/seeders/applications.ts
  src/seeders/index.ts
Labels: Ready For Review, DREAM TEAM

#131 fix (#160) : Admin Notifications
  package.json
  src/index.ts
  src/models/adminNotificationsModels.ts
  src/resolvers/adminNotificationsResolver.ts
  src/resolvers/applicationCycleResolver.ts
  src/resolvers/cohortResolver.ts
  src/resolvers/jobPostResolvers.ts
  src/resolvers/loginUserResolver.ts
  src/resolvers/programResolver.ts
  src/resolvers/traineeApplicantResolver.ts
  src/resolvers/userResolver.ts
  src/schema/adminNotificationsSchema.ts
Labels: Ready For Review, DREAM TEAM

#133 Ft tickets
  src/index.ts
  src/models/ticketModel.ts
  src/resolvers/filterTicketResolver.ts
  src/resolvers/ticketResolver.ts
  src/schema/ticketSchema.ts
  src/seeders/attendance.ts
  src/seeders/performance.ts
  src/seeders/users.ts
Labels: Ready For Review, BYTE SWAT
