Repository atlp-rwanda/atlp-devpulse-bn, pull requests merged in 2024-11, with the labels that each got.

#129 implementation of application stages #210
  src/index.ts
  src/models/InterviewAssessmentStageSchema.ts
  src/models/ShortlistedSchema.ts
  src/models/admittedStageSchema.ts
  src/models/dismissedStageSchema.ts
  src/models/stageSchema.ts
  src/models/technicalAssessmentStage.ts
  src/models/traineeApplicant.ts
  src/resolvers/applicationStageResolver.ts
  src/resolvers/appliedJobResolver.ts
  src/schema/applicationStage.ts
  src/schema/traineeApplicantSchema.ts
Labels: work-in-progress, BYTE SWAT

#132 fix(#156): Have a user be able to apply as a trainee
  src/models/traineeApplicant.ts
  src/models/traineeAttribute.ts
  src/resolvers/loginUserResolver.ts
  src/resolvers/traineeApplicantResolver.ts
  src/resolvers/traineeAttributeResolver.ts
  src/schema/loggedUser.ts
  src/schema/traineeApplicantSchema.ts
  src/schema/traineeAttributeSchema.ts
Labels: Ready For Review, DREAM TEAM

#136 fix timestamp for application stage action
  src/index.ts
  src/models/InterviewAssessmentStageSchema.ts
  src/models/ShortlistedSchema.ts
  src/models/admittedStageSchema.ts
  src/models/dismissedStageSchema.ts
  src/models/stageSchema.ts
  src/models/technicalAssessmentStage.ts
  src/models/traineeApplicant.ts
  src/resolvers/applicationStageResolver.ts
  src/resolvers/traineeApplicantResolver.ts
  src/schema/applicationStage.ts
  src/schema/traineeApplicantSchema.ts
  src/seeders/DelTrainee.ts
  src/seeders/index.ts
Labels: Ready For Review, BYTE SWAT

#144 fix attributes not being shown when admin view trainee data
  src/resolvers/traineeApplicantResolver.ts
Labels: work-in-progress, DREAM TEAM

#145 Ft blogger
  src/index.ts
  src/models/CommentReply.ts
  src/models/blogModel.ts
  src/models/commentLike.ts
  src/models/commentModel.ts
  src/models/likeModel.ts
  src/resolvers/blogResolvers.ts
  src/resolvers/commentLikeResolvers.ts
  src/resolvers/commentReplyResolvers.ts
  src/resolvers/commentResolvers.ts
  src/resolvers/likeResolvers.ts
  src/schema/blogSchema.ts
  src/schema/commentLikeSchema.ts
  src/schema/commentReplySchema.ts
  src/schema/commentSchema.ts
  src/schema/likeSchema.ts
  src/types/blogType.ts
  src/types/commentLikeType.ts
  src/types/commentReplyType.ts
  src/types/commentType.ts
  src/types/likeType.ts
  src/types/userType.ts
Labels: Ready For Review, DREAM TEAM

#142 Applicant should be able to apply to job post
  src/index.ts
  src/models/JobApplication.ts
  src/resolvers/jobApplicationResolver.ts
  src/schema/jobApplicationSchema.ts
Labels: Ready For Review, DREAM TEAM

#143 update applicant status to Admitted/Accepted and change role to trainee
  src/models/traineeApplicant.ts
  src/resolvers/applicationStageResolver.ts
  src/schema/traineeApplicantSchema.ts
  src/seeders/users.ts
Labels: Ready For Review, DREAM TEAM

#148 Integrate related ads with blog content
  src/index.ts
  src/resolvers/blogRelatedArticlesResolver.ts
  src/schema/blogRelatedArticlesSchema.ts
Labels: Ready For Review, DREAM TEAM

#151 Fix error in Job Application Schema
  src/schema/jobApplicationSchema.ts
Labels: bug, Ready For Review, DREAM TEAM

#152 allow trainee to create blog
  src/resolvers/blogResolvers.ts
Labels: Ready For Review, DREAM TEAM

#135 Ft notifications tickets cycle
  src/index.ts
  src/models/dismissedStageSchema.ts
  src/resolvers/applicationStageResolver.ts
  src/resolvers/ticketResolver.ts
  src/schema/applicationStage.ts
  src/schema/ticketSchema.ts
Labels: Ready For Review, BYTE SWAT

#156 Fix add code to update loggedusermodel
  src/resolvers/applicationStageResolver.ts
  src/seeders/blogs.ts
  src/seeders/index.ts
Labels: Ready For Review, DREAM TEAM

#159 Revert "ft: Generate API Documentation (#146)"
  .env.example
  README.md
  package.json
  public/assets/apple-touch-icon.png
  public/assets/devpulse.svg
  public/assets/favicon-96x96.png
  public/assets/favicon.ico
  public/assets/favicon.svg
  public/assets/site.webmanifest
  public/assets/web-app-manifest-192x192.png
  public/assets/web-app-manifest-512x512.png
  public/css/doc.css
  public/css/style.css
  public/documentation.html
  public/index.html
  src/index.ts
  tsconfig.json
Labels: Ready For Review, DREAM TEAM

#147 #250 Add documentation feature
  src/index.ts
  src/models/doc.ts
  src/resolvers/Doc.ts
  src/schema/doc.ts
Labels: Ready For Review, BYTE SWAT

#153 Admin should be able to hide a blog
  src/resolvers/blogResolvers.ts
  src/schema/blogSchema.ts
Labels: Ready For Review, DREAM TEAM

#160 #266 A user should be able to comment and react to a blog
  src/index.ts
  src/models/blogModel.ts
  src/models/commentModel.ts
  src/models/reactionModel.ts
  src/resolvers/blogResolvers.ts
  src/resolvers/commentLikeResolvers.ts
  src/resolvers/commentReplyResolvers.ts
  src/resolvers/commentResolvers.ts
  src/resolvers/reactionResolvers.ts
  src/schema/blogSchema.ts
  src/schema/commentLikeSchema.ts
  src/schema/commentSchema.ts
  src/schema/reactionSchema.ts
  src/types/reactionType.ts
Labels: Ready For Review, DREAM TEAM

#162 #161 fixing trainee-applicants page issue
  src/models/traineeApplicant.ts
  src/seeders/DelTrainee.ts
  src/seeders/applications.ts
Labels: Ready For Review, DREAM TEAM

#149 Implemented invitation functionality
  src/models/AuthUser.ts
  src/models/ShortlistedSchema.ts
  src/models/technicalAssessmentStage.ts
  src/resolvers/Doc.ts
  src/resolvers/applicationStageResolver.ts
  src/schema/applicationStage.ts
  src/schema/traineeApplicantSchema.ts
  src/seeders/users.ts
Labels: Ready For Review, BYTE SWAT
